<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitySeeder extends Seeder
{
    public function run()
    {
        $activities = [
        //Menurunkan BB
            [
                'name' => 'Jogging 30 menit',
                'calories_burned' => 250,
                'intensity' => 3,
                'description' => 'Lari santai 6 km/jam selama 30 menit di jalan datar.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Sepatu Lari']),
                'muscle_groups' => json_encode(['Kaki', 'Jantung']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.acsm.org/jogging-benefits',
            ],
            [
                'name' => 'Bersepeda Cepat 45 menit',
                'calories_burned' => 350,
                'intensity' => 3,
                'description' => 'Kayuh sepeda 15–20 km/jam di rute datar selama 45 menit.',
                'duration' => '45 menit',
                'equipment' => json_encode(['Sepeda']),
                'muscle_groups' => json_encode(['Kaki', 'Paha']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.healthline.com/nutrition/cycling-benefits',
            ],
            [
                'name' => 'Senam Aerobik 30 menit',
                'calories_burned' => 300,
                'intensity' => 3,
                'description' => 'Senam Zumba atau Poco-poco dengan gerakan penuh energi.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Seluruh Tubuh']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.acsm.org/aerobic-exercise',
            ],
            [
                'name' => 'Berenang 30 menit',
                'calories_burned' => 300,
                'intensity' => 3,
                'description' => 'Gaya bebas di kolam renang, kecepatan sedang-tinggi.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Kolam Renang', 'Baju Renang']),
                'muscle_groups' => json_encode(['Lengan', 'Punggung', 'Jantung']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.healthline.com/nutrition/swimming-benefits',
            ],
            [
                'name' => 'Jalan Santai 30 menit',
                'calories_burned' => 120,
                'intensity' => 1,
                'description' => 'Jalan kaki santai 4 km/jam di taman atau komplek.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Sepatu']),
                'muscle_groups' => json_encode(['Kaki']),
                'category' => 'Daily Activity',
                'reference_url' => 'https://www.healthline.com/nutrition/walking-benefits',
            ],
            [
                'name' => 'Berkebun 60 menit',
                'calories_burned' => 250,
                'intensity' => 2,
                'description' => 'Mencangkul, menanam, merapikan tanaman selama 1 jam.',
                'duration' => '60 menit',
                'equipment' => json_encode(['Alat Kebun']),
                'muscle_groups' => json_encode(['Seluruh Tubuh']),
                'category' => 'Daily Activity',
                'reference_url' => 'https://www.healthline.com/nutrition/gardening-exercise',
            ],
            [
                'name' => 'Membersihkan Rumah 30 menit',
                'calories_burned' => 150,
                'intensity' => 2,
                'description' => 'Mengepel, menyapu, mengatur barang selama 30 menit.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Alat Kebersihan']),
                'muscle_groups' => json_encode(['Seluruh Tubuh']),
                'category' => 'Daily Activity',
                'reference_url' => 'https://www.acsm.org/household-chores',
            ],
        
        //Menjaga BB
            [
                'name' => 'Jalan Cepat 30 menit',
                'calories_burned' => 180,
                'intensity' => 2,
                'description' => 'Jalan cepat 5 km/jam di rute datar atau ringan menanjak.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Sepatu']),
                'muscle_groups' => json_encode(['Kaki']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.healthline.com/nutrition/brisk-walking',
            ],
            [
                'name' => 'Bersepeda Santai 30 menit',
                'calories_burned' => 150,
                'intensity' => 2,
                'description' => 'Kayuh sepeda 10–12 km/jam di kompleks perumahan.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Sepeda']),
                'muscle_groups' => json_encode(['Kaki']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.acsm.org/cycling-moderate',
            ],
            [
                'name' => 'Senam Ringan 30 menit',
                'calories_burned' => 200,
                'intensity' => 2,
                'description' => 'Senam pagi dengan gerakan stretching dan penguatan ringan.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Seluruh Tubuh']),
                'category' => 'Strength',
                'reference_url' => 'https://www.healthline.com/nutrition/light-exercise',
            ],
            [
                'name' => 'Push-up & Squat 15 menit',
                'calories_burned' => 160,
                'intensity' => 2,
                'description' => '3 set push-up & 3 set squat, total 15 menit tanpa istirahat lama.',
                'duration' => '15 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Dada', 'Paha']),
                'category' => 'Strength',
                'reference_url' => 'https://www.mayoclinic.org/push-ups-squats',
            ],
            [
                'name' => 'Naik-Turun Tangga 20 menit',
                'calories_burned' => 180,
                'intensity' => 2,
                'description' => 'Naik turun tangga rumah atau gedung, tempo sedang.',
                'duration' => '20 menit',
                'equipment' => json_encode(['Tangga']),
                'muscle_groups' => json_encode(['Kaki', 'Paha']),
                'category' => 'Daily Activity',
                'reference_url' => 'https://www.healthline.com/nutrition/stair-climbing',
            ],
            [
                'name' => 'Sepak Takraw Ringan 30 menit',
                'calories_burned' => 180,
                'intensity' => 2,
                'description' => 'Bermain ringkas, rally santai tanpa pukulan keras.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Takraw']),
                'muscle_groups' => json_encode(['Kaki']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.healthline.com/nutrition/takraw-benefits',
            ],
            [
                'name' => 'Badminton Santai 30 menit',
                'calories_burned' => 200,
                'intensity' => 2,
                'description' => 'Rally ringan, tempo sedang, fokus ke kelincahan.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Raket', 'Shuttlecock']),
                'muscle_groups' => json_encode(['Lengan', 'Kaki']),
                'category' => 'Cardio',
                'reference_url' => 'https://www.acsm.org/badminton',
            ],

        //Meningkatkan BB
            [
                'name' => 'Latihan Beban 30 menit',
                'calories_burned' => 220,
                'intensity' => 2,
                'description' => 'Angkat beban dumbbell/barbel dengan repetisi sedang.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Dumbbell', 'Barbel']),
                'muscle_groups' => json_encode(['Lengan', 'Punggung']),
                'category' => 'Strength',
                'reference_url' => 'https://www.acsm.org/weight-training',
            ],
            [
                'name' => 'Push-up 3 set',
                'calories_burned' => 100,
                'intensity' => 2,
                'description' => '3 set push-up, masing-masing 8–12 ulang.',
                'duration' => '15 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Dada', 'Lengan']),
                'category' => 'Strength',
                'reference_url' => 'https://www.mayoclinic.org/push-ups',
            ],
            [
                'name' => 'Sit-up 3 set',
                'calories_burned' => 80,
                'intensity' => 2,
                'description' => '3 set sit-up, masing-masing 12–15 ulang.',
                'duration' => '15 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Perut']),
                'category' => 'Strength',
                'reference_url' => 'https://www.healthline.com/nutrition/sit-ups',
            ],
            [
                'name' => 'Squat 3 set',
                'calories_burned' => 120,
                'intensity' => 2,
                'description' => '3 set squat tubuh sendiri, masing-masing 12–15 ulang.',
                'duration' => '15 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Paha']),
                'category' => 'Strength',
                'reference_url' => 'https://www.acsm.org/squats',
            ],
            [
                'name' => 'Jalan Santai 30 menit',
                'calories_burned' => 120,
                'intensity' => 1,
                'description' => 'Jalan santai untuk pemulihan, tempo sangat ringan.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Sepatu']),
                'muscle_groups' => json_encode(['Kaki']),
                'category' => 'Daily Activity',
                'reference_url' => 'https://www.healthline.com/nutrition/walking-benefits',
            ],
            [
                'name' => 'Yoga Power 30 menit',
                'calories_burned' => 180,
                'intensity' => 2,
                'description' => 'Seri pose vinyasa yang menantang kekuatan otot.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Inti Tubuh', 'Fleksibilitas']),
                'category' => 'Strength',
                'reference_url' => 'https://www.healthline.com/nutrition/power-yoga',
            ],
            [
                'name' => 'Pilates 30 minit',
                'calories_burned' => 170,
                'intensity' => 2,
                'description' => 'Latihan core & fleksibilitas dengan alat ringkas.',
                'duration' => '30 menit',
                'equipment' => json_encode(['Matras']),
                'muscle_groups' => json_encode(['Inti Tubuh']),
                'category' => 'Strength',
                'reference_url' => 'https://www.acsm.org/pilates',
            ],
        ];

        foreach ($activities as $activity) {
            Activity::create($activity);
        }
    }
}