<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Food;

class FoodSeeder extends Seeder
{
    public function run()
    {
        $foods = [
        //Menurunkan BB
            [
                'name' => 'Nasi Merah',
                'calories' => 165,
                'description' => 'Karbohidrat kompleks tinggi serat',
                'portion' => '1 piring (150 g)',
                'meal_time' => json_encode(['Pagi', 'Siang']),
                'macro' => json_encode(['c' => 50, 'p' => 20, 'f' => 30]),
                'gi' => 50,
                'fiber' => 4,
                'image_url' => 'assets/images/nasi_merah.png',
                'reference_url' => 'https://www.usda.gov/fooddata/nasi-merah',
            ],
            [
                'name' => 'Ubi Jalar Rebus',
                'calories' => 120,
                'description' => 'Karbo kompleks, rendah GI',
                'portion' => '1 buah sedang (100 g)',
                'meal_time' => json_encode(['Pagi', 'Siang']),
                'macro' => json_encode(['c' => 60, 'p' => 10, 'f' => 30]),
                'gi' => 54,
                'fiber' => 3,
                'image_url' => 'assets/images/ubi_jalar.png',
                'reference_url' => 'https://www.healthline.com/nutrition/sweet-potato',
            ],
            [
                'name' => 'Bayam Tumis',
                'calories' => 40,
                'description' => 'Sayuran hijau, kaya zat besi',
                'portion' => '1 mangkuk (100 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 20, 'p' => 30, 'f' => 50]),
                'gi' => 15,
                'fiber' => 2,
                'image_url' => 'assets/images/bayam_tumis.png',
                'reference_url' => 'https://www.who.int/nutrition/spinach',
            ],
            [
                'name' => 'Pepaya',
                'calories' => 55,
                'description' => 'Buah rendah kalori, kaya vitamin C',
                'portion' => '1 Potong (100 g)',
                'meal_time' => json_encode(['Pagi']),
                'macro' => json_encode(['c' => 85, 'p' => 5, 'f' => 10]),
                'gi' => 54,
                'fiber' => 2,
                'image_url' => 'assets/images/pepaya.png',
                'reference_url' => 'https://www.healthline.com/nutrition/papaya',
            ],
            [
                'name' => 'Tahu Kukus',
                'calories' => 80,
                'description' => 'Protein nabati rendah lemak',
                'portion' => '2 Potong (100 g)',
                'meal_time' => json_encode(['Pagi', 'Siang', 'Malam']),
                'macro' => json_encode(['c' => 10, 'p' => 70, 'f' => 20]),
                'gi' => 15,
                'fiber' => 1,
                'image_url' => 'assets/images/tahu_kukus.png',
                'reference_url' => 'https://www.usda.gov/fooddata/tofu',
            ],
            [
                'name' => 'Jagung Rebus',
                'calories' => 90,
                'description' => 'Sumber karbo dan serat',
                'portion' => '1 tongkol sedang (100 g)',
                'meal_time' => json_encode(['Camilan']),
                'macro' => json_encode(['c' => 80, 'p' => 5, 'f' => 15]),
                'gi' => 52,
                'fiber' => 3,
                'image_url' => 'assets/images/jagung_rebus.png',
                'reference_url' => 'https://www.healthline.com/nutrition/boiled-corn',
            ],
            [
                'name' => 'Kacang Hijau Rebus',
                'calories' => 105,
                'description' => 'Protein & serat nabati — 100 g',
                'portion' => '100 g',
                'meal_time' => json_encode(['Camilan']),
                'macro' => json_encode(['c' => 60, 'p' => 30, 'f' => 10]),
                'gi' => 30,
                'fiber' => 6,
                'image_url' => 'assets/images/kacang_hijau.png',
                'reference_url' => 'https://www.usda.gov/fooddata/mung-beans',
            ],

        //Menjaga BB
            [
                'name' => 'Beras Merah',
                'calories' => 170,
                'description' => 'Karbo kompleks, serat sedang',
                'portion' => '1 piring (150 g)',
                'meal_time' => json_encode(['Pagi', 'Siang']),
                'macro' => json_encode(['c' => 65, 'p' => 15, 'f' => 20]),
                'gi' => 55,
                'fiber' => 3,
                'image_url' => 'assets/images/beras_merah.png',
                'reference_url' => 'https://www.usda.gov/fooddata/brown-rice',
            ],
            [
                'name' => 'Roti Gandum',
                'calories' => 90,
                'description' => 'Karbo serat tinggi',
                'portion' => '2 iris (60 g)',
                'meal_time' => json_encode(['Pagi', 'Siang']),
                'macro' => json_encode(['c' => 70, 'p' => 15, 'f' => 15]),
                'gi' => 50,
                'fiber' => 4,
                'image_url' => 'assets/images/roti_gandum.png',
                'reference_url' => 'https://www.healthline.com/nutrition/whole-grain-bread',
            ],
            [
                'name' => 'Kentang Rebus',
                'calories' => 150,
                'description' => 'Sumber karbo medium GI',
                'portion' => '1 buah sedang (150 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 80, 'p' => 10, 'f' => 10]),
                'gi' => 65,
                'fiber' => 2,
                'image_url' => 'assets/images/kentang_rebus.png',
                'reference_url' => 'https://www.usda.gov/fooddata/potato',
            ],
            [
                'name' => 'Ayam Tanpa Kulit',
                'calories' => 190,
                'description' => 'Protein rendah lemak',
                'portion' => '1 potong (100 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 0, 'p' => 90, 'f' => 10]),
                'gi' => 0,
                'fiber' => 0,
                'image_url' => 'assets/images/ayam_tanpa_kulit.png',
                'reference_url' => 'https://www.healthline.com/nutrition/chicken-breast',
            ],
            [
                'name' => 'Alpukat',
                'calories' => 160,
                'description' => 'Lemak sehat tak jenuh',
                'portion' => '1/2 buah (100 g)',
                'meal_time' => json_encode(['Pagi']),
                'macro' => json_encode(['c' => 15, 'p' => 5, 'f' => 80]),
                'gi' => 15,
                'fiber' => 7,
                'image_url' => 'assets/images/alpukat.png',
                'reference_url' => 'https://www.usda.gov/fooddata/avocado',
            ],
            [
                'name' => 'Tempe Goreng Ringan',
                'calories' => 180,
                'description' => 'Protein nabati, lemak sehat',
                'portion' => '3 iris (100 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 15, 'p' => 65, 'f' => 20]),
                'gi' => 15,
                'fiber' => 3,
                'image_url' => 'assets/images/tempe_goreng.png',
                'reference_url' => 'https://www.healthline.com/nutrition/tempeh',
            ],
            [
                'name' => 'Oatmeal',
                'calories' => 68,
                'description' => 'Serat larut, 100 g diseduh',
                'portion' => '1 mangkuk (200 ml)',
                'meal_time' => json_encode(['Pagi']),
                'macro' => json_encode(['c' => 80, 'p' => 10, 'f' => 10]),
                'gi' => 55,
                'fiber' => 4,
                'image_url' => 'assets/images/oatmeal.png',
                'reference_url' => 'https://www.healthline.com/nutrition/oatmeal-benefits',
            ],
            [
                'name' => 'Telur Rebus',
                'calories' => 78,
                'description' => 'Protein tinggi, satu butir sedang',
                'portion' => '1 butir (50 g)',
                'meal_time' => json_encode(['Pagi', 'Siang']),
                'macro' => json_encode(['c' => 0, 'p' => 90, 'f' => 10]),
                'gi' => 0,
                'fiber' => 0,
                'image_url' => 'assets/images/telur_rebus.png',
                'reference_url' => 'https://www.healthline.com/nutrition/boiled-egg',
            ],
        
        //Meningkatkan BB
            [
                'name' => 'Nasi Putih Porsi Besar',
                'calories' => 300,
                'description' => 'Karbohidrat padat energi',
                'portion' => '2 piring (300 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 80, 'p' => 10, 'f' => 10]),
                'gi' => 70,
                'fiber' => 2,
                'image_url' => 'assets/images/nasi_putih.png',
                'reference_url' => 'https://www.usda.gov/fooddata/white-rice',
            ],
            [
                'name' => 'Ayam Goreng',
                'calories' => 280,
                'description' => 'Protein & lemak tinggi',
                'portion' => '1 potong (120 g)',
                'meal_time' => json_encode(['Siang', 'Malam']),
                'macro' => json_encode(['c' => 0, 'p' => 40, 'f' => 60]),
                'gi' => 0,
                'fiber' => 0,
                'image_url' => 'assets/images/ayam_goreng.png',
                'reference_url' => 'https://www.healthline.com/nutrition/fried-chicken',
            ],
            [
                'name' => 'Pisang Goreng',
                'calories' => 200,
                'description' => 'Camilan padat energi',
                'portion' => '2 potong (80 g)',
                'meal_time' => json_encode(['Camilan']),
                'macro' => json_encode(['c' => 80, 'p' => 5, 'f' => 15]),
                'gi' => 75,
                'fiber' => 2,
                'image_url' => 'assets/images/pisang_goreng.png',
                'reference_url' => 'https://www.healthline.com/nutrition/fried-banana',
            ],
            [
                'name' => 'Roti Isi Selai',
                'calories' => 220,
                'description' => 'Karbo + lemak + gula',
                'portion' => '1 buah (60 g)',
                'meal_time' => json_encode(['Pagi', 'Camilan']),
                'macro' => json_encode(['c' => 60, 'p' => 5, 'f' => 35]),
                'gi' => 55,
                'fiber' => 1,
                'image_url' => 'assets/images/roti_selai.png',
                'reference_url' => 'https://www.healthline.com/nutrition/jam-filled-bread',
            ],
            [
                'name' => 'Bolu Kukus',
                'calories' => 250,
                'description' => 'Sayur + lemak sehat',
                'portion' => '1 mangkuk (200 ml)',
                'meal_time' => json_encode(['Malam']),
                'macro' => json_encode(['c' => 40, 'p' => 20, 'f' => 40]),
                'gi' => 35,
                'fiber' => 3,
                'image_url' => 'assets/images/lodeh.png',
                'reference_url' => 'https://www.healthline.com/nutrition/vegetable-coconut-curry',
            ],
            [
                'name' => 'Kacang Tanah Rebus',
                'calories' => 560,
                'description' => 'Lemak sehat & protein',
                'portion' => '(100 g)',
                'meal_time' => json_encode(['Camilan']),
                'macro' => json_encode(['c' => 10, 'p' => 20, 'f' => 70]),
                'gi' => 14,
                'fiber' => 8,
                'image_url' => 'assets/images/kacang_tanah.png',
                'reference_url' => 'https://www.healthline.com/nutrition/peanuts',
            ],
            [
                'name' => 'Cokelat Hitam (70%)',
                'calories' => 273,
                'description' => 'Lemak & gula — 100 g',
                'portion' => '2 potong (50 g)',
                'meal_time' => json_encode(['Camilan']),
                'macro' => json_encode(['c' => 40, 'p' => 5, 'f' => 55]),
                'gi' => 25,
                'fiber' => 5,
                'image_url' => 'assets/images/cokelat_hitam.png',
                'reference_url' => 'https://www.usda.gov/fooddata/dark-chocolate',
            ],
        ];

        foreach ($foods as $food) {
            Food::create($food);
        }
    }
}